name: grinch
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - wget
  - biopython=1.74
  - minimap2
  - pip=19.3.1
  - python=3.7
  - snakemake-minimal=5.13
  - libpysal=4.3.0
  - nodejs=10.12.0
  - pip:
    - pandas>=1.1.0
    - pytools==2020.1
    - tabulate>=0.8.7
    - descartes>=1.1.0
    - adjustText>=0.7.3
    - git+https://github.com/cov-ert/fastafunk.git
    - git+https://github.com/cov-ert/datafunk.git
    - git+https://github.com/cov-ert/reportfunk.git
    - git+https://github.com/cov-lineages/pangolin.git
    - git+https://github.com/cov-lineages/lineages.git
    - git+https://github.com/cov-lineages/pangoLEARN.git